---
ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - host: headlamp.lan
      paths:
        - path: /
          type: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  tls:
    - secretName: headlamp-tls
      hosts:
        - headlamp.lan
