---
services:
  romm:
    image: ghcr.io/rommapp/romm:4.4.0
    container_name: romm
    hostname: pi
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.romm.service=romm"
        - "traefik.http.routers.romm.rule=Host(`romm.lan`)"
        - "traefik.http.services.romm.loadbalancer.server.port=80"
        - "traefik.http.routers.romm.entrypoints=web"

networks:
  homelab:
    external: true
